### ISSUE TITLE
Free ordering of clauses

### ISSUE THREAD

**Issue by dryewo** [rufoa/try-let#2]
I stumbled upon your library and liked it very much! It resonated with me.

I had the same idea about `try` with the following features:
* doesn't cover `act-on-value` - you got it right already
* error handling code goes first

I'd like to elaborate on the second case.

In a standard try-let code we have something like this:

```clj
(try-let [x1 (get-x1)]
  (try-let [x2 (calc-x2 x1)]
    (try-let [x3 (transform-x3 x2)]
      x3
      (catch Exception _
        (println "Problem obtaining x3")))
    (catch Exception _
      (println "Problem obtaining x2")))
  (catch Exception _
    (println "Problem obtaining x1")))
```

And then you try to read it and think "well, here we try to `calc-x2`, but what happens if it throws?.." then you scroll half a page and painfully squint trying to match the indents to see the corresponding catch among other catches. Original `try` has the same problem. I think one can refer to this type of code as `>`-shaped.

IMHO, the following equivalent code is much easier to read:

```clj
(try-let [x1 (get-x1)]
  (catch Exception _
    (println "Problem obtaining x1"))
  (try-let [x2 (calc-x2 x1)]
    (catch Exception _
      (println "Problem obtaining x2"))
    (try-let [x3 (transform-x3 x2)]
      (catch Exception _
        (println "Problem obtaining x3"))
      x3)))
```

This code is `\`-shaped, it reads nicely and linearly, its result is in the last line, and no problems understanding how errors are handled.

What do you think?

It can be quite easily be implemented in the macro logic by just reordering the body of try-let, putting all catches in the end and all non-catches before them. I would love to submit a PR, but wanted to get your opinion first.

**Comment by rufoa** [comment]
Sounds good to me! I'd happily accept a PR that adds this alternative syntax

**Comment by rufoa** [comment]
nvm just did it myself - please upgrade to `1.3.0` and check it works as expected

**Comment by dryewo** [comment]
Ahaha!
Just 5 minutes ago I prepared this: https://github.com/dryewo/try-let/commit/853bd9a8560eace2ef6cae82c7aab16b191e4a06
It looks like you did a more elaborate job.
Thanks a lot!

**Comment by rufoa** [comment]
Ha, sorry! I'll merge your readme changes. Thanks for your feedback and work

**Comment by dryewo** [comment]
Great, I just wanted to suggest the readme.
Thanks again!
